# Generated by Django 4.1.2 on 2022-10-29 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicblog', '0002_remove_lyric_artiste_remove_lyric_song_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='Artiste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicblog.artiste'),
        ),
    ]
